import javax.swing.*;

public class Ventana {
    private JTabbedPane tabbedPane1;
    private JPanel panel1;
    private JComboBox comboBox1;
    private JTextField textField1;
    private JTextField textField2;
    private JComboBox comboBox2;
    private JList list1;
    private JButton agregarButton;
    private JButton eliminarButton;
    private JButton modificarButton;
    private JButton buscarButton;
    private JTextField textField3;
    private JTextField textField4;
    private JComboBox comboBox3;
    private JComboBox comboBox4;
    private JButton agregarButton1;
    private JButton eliminarButton1;
    private JButton modificarButton1;
    private JButton buscarButton1;
    private JList list2;
    private JComboBox comboBox5;
    private JComboBox comboBox6;
    private JTextField textField5;
    private JTextField textField6;
    private JButton agregarButton2;
    private JButton eliminarButton2;
    private JButton modificarButton2;
    private JButton buscarButton2;
    private JList list3;
    private JComboBox comboBox7;
    private JComboBox comboBox8;
    private JTextField textField7;
    private JTextField textField8;
    private JButton agregarButton3;
    private JButton eliminarButton3;
    private JButton modificarButton3;
    private JButton buscarButton3;
    private JList list4;
    private JList list5;
    private JButton ordenarPorCodigoButton;
    private JButton ordenarPorPrecioButton;
    private JList list6;
    private JList list7;
}
